//! Does the VAD actually fire on real speech?
//!
//! Production logs showed `(speech detected)` never printing across
//! whole dictation sessions -- meaning `Endpointer` never confirmed
//! speech, so the streaming decode path (§2.2: "trim silence so the
//! encoder never wastes compute on dead air") never engaged at all and
//! *everything* was left to the single decode at hotkey release. That is
//! the entire streaming design silently not running.
//!
//! This isolates the question: given unambiguous speech, does
//! `SileroVad` return high probabilities and does `Endpointer` confirm a
//! start? If yes, the bug is upstream (mic levels, framing, feeding).
//! If no, it's in this crate.
//!
//! Fixture is generated by Windows TTS -- see
//! `crates/asr/tests/audio_ctx_quality.rs`'s module docs for the
//! one-liner. Run:
//!
//! VAD_BENCH_MODEL=models/silero_vad.onnx VAD_SPEECH_WAV=<path to speech_hey.wav> \
//!   cargo test --release -p vad --test real_speech_probe -- --ignored --nocapture

use vad::{next_frame_range, EndpointConfig, EndpointEvent, Endpointer, SileroVad};

fn read_wav_16k_mono(path: &str) -> Vec<f32> {
    let bytes = std::fs::read(path).expect("fixture wav should exist");
    let mut pos = 12;
    while pos + 8 <= bytes.len() {
        let id = &bytes[pos..pos + 4];
        let size = u32::from_le_bytes([bytes[pos + 4], bytes[pos + 5], bytes[pos + 6], bytes[pos + 7]]) as usize;
        let body = pos + 8;
        if id == b"data" {
            let end = (body + size).min(bytes.len());
            return bytes[body..end]
                .chunks_exact(2)
                .map(|s| i16::from_le_bytes([s[0], s[1]]) as f32 / 32768.0)
                .collect();
        }
        pos = body + size + (size & 1);
    }
    panic!("no data chunk in {path}");
}

#[test]
#[ignore]
fn speech_probabilities_and_confirmed_start() {
    let (Ok(model_path), Ok(wav_path)) = (
        std::env::var("VAD_BENCH_MODEL"),
        std::env::var("VAD_SPEECH_WAV"),
    ) else {
        eprintln!("set VAD_BENCH_MODEL and VAD_SPEECH_WAV to run this probe");
        return;
    };

    let audio = read_wav_16k_mono(&wav_path);
    let peak = audio.iter().fold(0.0f32, |m, s| m.max(s.abs()));
    let rms = (audio.iter().map(|s| s * s).sum::<f32>() / audio.len() as f32).sqrt();
    println!(
        "fixture: {:.2}s, peak amplitude {peak:.3}, rms {rms:.4}\n",
        audio.len() as f64 / 16_000.0
    );

    // Print the ONNX signature before anything else: the production bug
    // was a name mismatch (code written against Silero v4's h/c inputs,
    // model file is v5), and that's invisible until you look.
    {
        let session = ort::session::Session::builder()
            .expect("builder")
            .commit_from_file(&model_path)
            .expect("model should load");
        let ins: Vec<&str> = session.inputs().iter().map(|i| i.name()).collect();
        let outs: Vec<&str> = session.outputs().iter().map(|o| o.name()).collect();
        println!("onnx inputs:  {ins:?}");
        println!("onnx outputs: {outs:?}");
        for i in session.inputs() {
            println!("  in  {:>6}: {:?}", i.name(), i.dtype());
        }
        for o in session.outputs() {
            println!("  out {:>6}: {:?}", o.name(), o.dtype());
        }
        println!();
    }

    // Direct ORT call, bypassing SileroVad entirely: separates "our
    // wrapper is wrong" from "these tensor shapes are wrong". Tries `sr`
    // as a rank-1 tensor (what the wrapper sends) against a true scalar,
    // which is what Silero v5's signature actually declares.
    {
        use ort::value::Tensor;
        let mut session = ort::session::Session::builder()
            .expect("builder")
            .commit_from_file(&model_path)
            .expect("model should load");
        // A frame from the middle of the clip, where speech definitely is.
        let mid = (audio.len() / 2) & !511;
        let frame: Vec<f32> = audio[mid..mid + 512].to_vec();

        // Wildly different inputs: if the probability barely moves, the
        // audio isn't reaching the model at all (a binding problem), not
        // "the model disagrees about this audio".
        let silence = vec![0.0_f32; 512];
        let noise: Vec<f32> = (0..512).map(|i| ((i * 7919) % 2000) as f32 / 1000.0 - 1.0).collect();
        for (label, samples) in [
            ("silence     ", &silence),
            ("real speech ", &frame),
            ("white-ish   ", &noise),
        ] {
            let input = Tensor::from_array(([1_i64, 512], samples.clone())).unwrap();
            let state = Tensor::from_array(([2_i64, 1, 128], vec![0.0_f32; 2 * 128])).unwrap();
            let sr = Tensor::from_array(([0_i64; 0], vec![16_000_i64])).unwrap();
            match session.run(ort::inputs!["input" => input, "state" => state, "sr" => sr]) {
                Ok(out) => {
                    let (_, p) = out["output"].try_extract_tensor::<f32>().unwrap();
                    let rms = (samples.iter().map(|s| s * s).sum::<f32>() / 512.0).sqrt();
                    println!("direct call, {label}(rms {rms:.3}): probability {:.4}", p[0]);
                }
                Err(e) => println!("direct call, {label}: ERROR {e}"),
            }
        }
        println!();
    }

    let mut vad = SileroVad::load(&model_path).expect("vad model should load");
    let mut endpointer = Endpointer::new(EndpointConfig::default());

    let mut fed = 0usize;
    let mut probs = Vec::new();
    let mut first_start_frame = None;
    let mut frame_index = 0usize;

    while let Some((start, end)) = next_frame_range(fed, audio.len()) {
        let p = vad.process_frame(&audio[start..end]).expect("frame should process");
        probs.push(p);
        if let Some(EndpointEvent::SpeechStart) = endpointer.push_probability(p) {
            first_start_frame.get_or_insert(frame_index);
        }
        fed = end;
        frame_index += 1;
    }

    let max = probs.iter().cloned().fold(0.0f32, f32::max);
    let over_half = probs.iter().filter(|&&p| p > 0.5).count();
    println!("frames: {}", probs.len());
    println!("max probability: {max:.3}");
    println!("frames over 0.5 (the default speech_threshold): {over_half}");
    println!("first 12 probabilities: {:?}", probs.iter().take(12).map(|p| (p * 100.0).round() / 100.0).collect::<Vec<_>>());
    match first_start_frame {
        Some(f) => println!("\nSpeechStart confirmed at frame {f} -- VAD path is working."),
        None => println!("\nNO SpeechStart EVER CONFIRMED -- this reproduces the production bug."),
    }
}
